version: 4.2.{build}

os: Visual Studio 2015

environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

platform:
  - x64

configuration:
  - Release

install:
  - cmake --version
  - git submodule -q update --init

before_build:
  - md %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G"%VSVER%" -DBUILD_META_EXAMPLES=OFF ..
  - cd ..

build:
  parallel: true
  project: build\shogun.sln

test_script:
  - cd build
  - ctest -V
  - cd ..\..
